version: '3.9'

services:
  encode-service:
    build:
      context: .
      dockerfile: Dockerfile.encode
    ports:
      - "8000:8000"
    env_file:
      - .env

  search-service:
    build:
      context: .
      dockerfile: Dockerfile.search
    ports:
      - "8001:8001"
    env_file:
      - path: .env

