FROM python:3.8-slim
WORKDIR /app
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    git \
    libgl1-mesa-glx \
    libglib2.0-0 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .


EXPOSE 8000


CMD ["uvicorn", "encode_service.encode:app", "--host", "0.0.0.0", "--port", "8000"]