version: '3.8'

services:
  encode-service:
    build:
      context: .
      dockerfile: Dockerfile.encode
    ports:
      - "8000:8000"
    volumes:
      - data:/data

  search-service:
    build:
      context: .
      dockerfile: Dockerfile.search
    ports:
      - "8001:8001"
    env_file:
      - .env
    volumes:
      - data:/data

volumes:
  data:
